workflows:
  android-apk:
    name: V写作 Android APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Create missing platform files
        script: |
          flutter create .
      - name: Get packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
